### ISSUE TITLE
Make a better response

### ISSUE THREAD

**Issue by wdrach** [MotelIs/swaggest-test#1]
Response should be selected from the original method responses rather than defining a new one, such as 
``` yaml
response:
  '200':
    parameters:
      message: 'success'
```

**Comment by wdrach** [comment]
```yaml
response:
  '200':
    headers:
      'content-type': 'application/json'
    parameters:
      message: 'success'
```

We should be checking to enforce typing and requirements as specified in the response schema, regardless of what information we're given.
